export const SET_LOADING = 'SET_LOADING';

export const GET_ALL_LISTINGS_BEGIN = 'GET_ALL_LISTINGS_BEGIN';
export const GET_ALL_LISTINGS_SUCCESS = 'GET_ALL_LISTINGS_SUCCESS';

export const GET_ALL_LISTINGS_LOCATIONS_BEGIN =
  'GET_ALL_LISTINGS_LOCATIONS_BEGIN';
export const GET_ALL_LISTINGS_LOCATIONS_SUCCESS =
  'GET_ALL_LISTINGS_LOCATIONS_SUCCESS';

export const GET_LISTINGS_BY_USER_BEGIN = 'GET_LISTINGS_BY_USER_BEGIN';
export const GET_LISTINGS_BY_USER_SUCCESS = 'GET_LISTINGS_BY_USER_SUCCESS';

export const GET_MY_LISTINGS_BEGIN = 'GET_MY_LISTINGS_BEGIN';
export const GET_MY_LISTINGS_SUCCESS = 'GET_MY_LISTINGS_SUCCESS';

export const GET_FILTERED_LISTINGS_BEGIN = 'GET_FILTERED_LISTINGS_BEGIN';
export const GET_FILTERED_LISTINGS_SUCCESS = 'GET_FILTERED_LISTINGS_SUCCESS';

export const GET_OFFER_LISTINGS_BEGIN = 'GET_OFFER_LISTINGS_BEGIN';
export const GET_OFFER_LISTINGS_SUCCESS = 'GET_OFFER_LISTINGS_SUCCESS';

export const GET_MORE_OFFER_LISTINGS_BEGIN = 'GET_MORE_OFFER_LISTINGS_BEGIN';
export const GET_MORE_OFFER_LISTINGS_SUCCESS =
  'GET_MORE_OFFER_LISTINGS_SUCCESS';

export const GET_MORE_TYPE_LISTINGS_BEGIN = 'GET_MORE_TYPE_LISTINGS_BEGIN';
export const GET_MORE_TYPE_LISTINGS_SUCCESS = 'GET_MORE_TYPE_LISTINGS_SUCCESS';

export const GET_RENT_LISTINGS_BEGIN = 'GET_RENT_LISTINGS_BEGIN';
export const GET_RENT_LISTINGS_SUCCESS = 'GET_RENT_LISTINGS_SUCCESS';

export const GET_SALE_LISTINGS_BEGIN = 'GET_SALE_LISTINGS_BEGIN';
export const GET_SALE_LISTINGS_SUCCESS = 'GET_SALE_LISTINGS_SUCCESS';

export const GET_TYPE_LISTINGS_BEGIN = 'GET_TYPE_LISTINGS_BEGIN';
export const GET_TYPE_LISTINGS_SUCCESS = 'GET_TYPE_LISTINGS_SUCCESS';

export const GET_LISTING_BEGIN = 'GET_LISTING_BEGIN';
export const GET_LISTING_SUCCESS = 'GET_LISTING_SUCCESS';

export const CREATE_LISTING_BEGIN = 'CREATE_LISTING_BEGIN';
export const CREATE_LISTING_SUCCESS = 'CREATE_LISTING_SUCCESS';
export const CREATE_LISTING_ERROR = 'CREATE_LISTING_ERROR';

export const EDIT_LISTING_BEGIN = 'EDIT_LISTING_BEGIN';
export const EDIT_LISTING_SUCCESS = 'EDIT_LISTING_SUCCESS';
export const EDIT_LISTING_ERROR = 'EDIT_LISTING_ERROR';

export const DELETE_LISTING_BEGIN = 'DELETE_LISTING_BEGIN';
export const DELETE_LISTING_SUCCESS = 'DELETE_LISTING_SUCCESS';
export const DELETE_LISTING_ERROR = 'DELETE_LISTING_ERROR';

export const ADD_LISTING_TO_FAVORITES = 'ADD_LISTING_TO_FAVORITES';
export const REMOVE_LISTING_FROM_FAVORITES = 'REMOVE_LISTING_FROM_FAVORITES';
export const REMOVE_ALL_FAVORITES = 'REMOVE_ALL_FAVORITES';
