export const GET_ALL_PROFILES_BEGIN = 'GET_ALL_PROFILES_BEGIN';
export const GET_ALL_PROFILES_SUCCESS = 'GET_ALL_PROFILES_SUCCESS';

export const GET_USER_PROFILE_BEGIN = 'GET_USER_PROFILE_BEGIN';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_ERROR = 'GET_USER_PROFILE_ERROR';

export const GET_MY_PROFILE_BEGIN = 'GET_MY_PROFILE_BEGIN';
export const GET_MY_PROFILE_SUCCESS = 'GET_MY_PROFILE_SUCCESS';
export const GET_MY_PROFILE_ERROR = 'GET_MY_PROFILE_ERROR';

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const CHANGE_USER_ROLE_BEGIN = 'CHANGE_USER_ROLE_BEGIN';
export const CHANGE_USER_ROLE_SUCCESS = 'CHANGE_USER_ROLE_SUCCESS';
export const CHANGE_USER_ROLE_ERROR = 'CHANGE_USER_ROLE_ERROR';
