export const SET_LOADING = 'SET_LOADING';

export const GET_ALL_SUBSCRIPTIONS_BEGIN = 'GET_ALL_SUBSCRIPTIONS_BEGIN';
export const GET_ALL_SUBSCRIPTIONS_SUCCESS = 'GET_ALL_SUBSCRIPTIONS_SUCCESS';

export const GET_SUBSCRIPTIONS_BY_USER_BEGIN =
  'GET_SUBSCRIPTIONS_BY_USER_BEGIN';
export const GET_SUBSCRIPTIONS_BY_USER_SUCCESS =
  'GET_SUBSCRIPTIONS_BY_USER_SUCCESS';

export const GET_MY_SUBSCRIPTIONS_BEGIN = 'GET_MY_SUBSCRIPTIONS_BEGIN';
export const GET_MY_SUBSCRIPTIONS_SUCCESS = 'GET_MY_SUBSCRIPTIONS_SUCCESS';

export const GET_PLAN_SUBSCRIPTIONS_BEGIN = 'GET_PLAN_SUBSCRIPTIONS_BEGIN';
export const GET_PLAN_SUBSCRIPTIONS_SUCCESS = 'GET_PLAN_SUBSCRIPTIONS_SUCCESS';

export const GET_SUBSCRIPTION_BEGIN = 'GET_SUBSCRIPTION_BEGIN';
export const GET_SUBSCRIPTION_SUCCESS = 'GET_SUBSCRIPTION_SUCCESS';

export const CREATE_SUBSCRIPTION_BEGIN = 'CREATE_SUBSCRIPTION_BEGIN';
export const CREATE_SUBSCRIPTION_SUCCESS = 'CREATE_SUBSCRIPTION_SUCCESS';
export const CREATE_SUBSCRIPTION_ERROR = 'CREATE_SUBSCRIPTION_ERROR';

export const EDIT_SUBSCRIPTION_BEGIN = 'EDIT_SUBSCRIPTION_BEGIN';
export const EDIT_SUBSCRIPTION_SUCCESS = 'EDIT_SUBSCRIPTION_SUCCESS';
export const EDIT_SUBSCRIPTION_ERROR = 'EDIT_SUBSCRIPTION_ERROR';

export const DELETE_SUBSCRIPTION_BEGIN = 'DELETE_SUBSCRIPTION_BEGIN';
export const DELETE_SUBSCRIPTION_SUCCESS = 'DELETE_SUBSCRIPTION_SUCCESS';
export const DELETE_SUBSCRIPTION_ERROR = 'DELETE_SUBSCRIPTION_ERROR';
