const floors = [
  {
    id: '0',
    code: 'none',
    floor: -2,
    shortName: 'none',
    enum: 'none',
    title: 'none',
    value: 0,
  },
  {
    id: '1',
    code: 'base',
    floor: -1,
    shortName: 'base',
    enum: 'base',
    title: 'basement',
    value: 1,
  },
  {
    id: '2',
    code: 'ground',
    floor: 0,
    shortName: 'ground',
    enum: 'ground',
    title: 'ground-floor',
    value: 2,
  },
  {
    id: '3',
    code: '1st',
    floor: 1,
    shortName: 'first',
    enum: 'first',
    title: 'first-floor',
    value: 3,
  },
  {
    id: '4',
    code: '2nd',
    floor: 2,
    shortName: 'second',
    enum: 'second',
    title: 'second-floor',
    value: 4,
  },
  {
    id: '5',
    code: '3rd',
    floor: 3,
    shortName: 'third',
    enum: 'third',
    title: 'third-floor',
    value: 5,
  },
  {
    id: '6',
    code: '4th',
    floor: 4,
    shortName: 'forth',
    enum: 'forth',
    title: 'forth-floor',
    value: 6,
  },
  {
    id: '7',
    code: '5th',
    floor: 5,
    shortName: 'fifth',
    enum: 'fifth',
    title: 'fifth-floor',
    value: 7,
  },
];

export default floors;
