const roles = [
  {
    id: '1',
    title: 'user',
    txtColor: 'text-user-500',
    txtColorLight: 'text-user-100',
    brdColor: 'border-user-500',
    bgColor: 'bg-user-500',
    bgColorLight: 'bg-user-100',
    shadow: '',
    enum: 'user',
  },
  {
    id: '2',
    title: 'owner',
    txtColor: 'text-owner-500',
    txtColorLight: 'text-owner-100',
    brdColor: 'border-owner-500',
    bgColor: 'bg-owner-500',
    bgColorLight: 'bg-owner-100',
    shadow: 'shadow-[0_0_5px_0_rgba(94,142,162,0.5)]',
    enum: 'owner',
  },
  {
    id: '3',
    title: 'real-estater',
    txtColor: 'text-real-estater-500',
    txtColorLight: 'text-real-estater-100',
    brdColor: 'border-real-estater-500',
    bgColor: 'bg-real-estater-500',
    bgColorLight: 'bg-real-estater-100',
    shadow: 'shadow-[0_0_5px_0_rgba(255,105,34,0.5)]',
    enum: 'real-estater',
  },
  {
    id: '4',
    title: 'agent',
    txtColor: 'text-agent-500',
    txtColorLight: 'text-agent-100',
    brdColor: 'border-agent-500',
    bgColor: 'bg-agent-500',
    bgColorLight: 'bg-agent-100',
    shadow: 'shadow-[0_0_5px_0_rgba(11,183,146,0.5)]',
    enum: 'agent',
  },
  {
    id: '5',
    title: 'admin',
    txtColor: 'text-admin-500',
    txtColorLight: 'text-admin-100',
    brdColor: 'border-admin-500',
    bgColor: 'bg-admin-500',
    bgColorLight: 'bg-admin-100',
    shadow: 'shadow-[0_0_5px_0_rgba(0,134,189,0.5)]',
    enum: 'admin',
  },
];

export default roles;
